CREATE TABLE [dbo].[Cart]
(
	[CartId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(UserId) ON DELETE CASCADE NOT NULL,
	Quantity INT NULL,
	CreatedDate DATETIME NOT NULL
)
