CREATE TABLE [dbo].[Orders]
(
	[OrderDetailsId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[OrderNo] VARCHAR(MAX) NULL,
	[ProductId] INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	[Quantity] INT NULL,
	[UserId] INT FOREIGN KEY REFERENCES Users(UserId) ON DELETE CASCADE NOT NULL,
	[Status] VARCHAR(50) NULL,
	[PaymentId] INT FOREIGN KEY REFERENCES Payment(PaymentId) ON DELETE CASCADE NOT NULL,
	[OrderDate] DATETIME NULL,
	[IsCancel] BIT NOT NULL DEFAULT 0 

)
