CREATE TABLE [dbo].[ProductReview]
(
   ReviewId INT PRIMARY KEY IDENTITY(1,1),
   Rating INT NOT NULL,
   Comment VARCHAR(MAX) NULL,
   ProductId INT FOREIGN KEY REFERENCES Product (ProductId) ON DELETE CASCADE NOT NULL,
   UserId INT FOREIGN KEY REFERENCES Users (UserId) ON DELETE CASCADE NOT NULL,
   CreatedDate DATETIME NOT NULL

)
