CREATE TABLE [dbo].[Users]
(
   UserId INT PRIMARY KEY IDENTITY(1,1),
   Name VARCHAR(50) NULL,
   UserName VARCHAR(50) UNIQUE,
   Mobile VARCHAR(30) NULL,
   Email VARCHAR(50) NULL,
   Address VARCHAR(MAX) NULL,
   PostCode VARCHAR(50) NULL,
   Password VARCHAR(50) NULL,
   ImageUrl VARCHAR(MAX) NULL,
   RoleId INT FOREIGN KEY REFERENCES Roles(RoleId) ON DELETE CASCADE NOT NULL,
   CreatedDate DATETIME NOT NULL
)
