CREATE TABLE [dbo].[WishList]
(
	[WishListId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(UserId) ON DELETE CASCADE NOT NULL,
	CreatedDate DATETIME NOT NULL 
)
